#!/usr/bin/env python3
"""upstream/MucomWeb/mucom88/src/bin_voice.h (bin_voice_dat, C配列リテラル) をパースし、
MUCOM88既定音色バンク(256スロット)の「スロット番号 -> 音色名(生バイト列)」表を
ui/mucom-voice-table.js としてES module出力する。

背景: MUCOM88のZ80コンパイラは `@"名前"` 形式の音色参照で非ASCIIバイト(半角カナ等)を
扱えず `FM Voice not found` で落ちることが実測で判明している(ui/mucom-voice-resolve.js
参照)。`@番号`(数値指定)はn=0..255全件が通ることも実測済みのため、`@"名前"` を該当
スロットの `@番号` へ事前置換して回避する。この置換に使う「名前 -> スロット番号」表を
ビルド時に生成するのが本スクリプト。

データ形式(出典: upstream/MucomWeb/mucom88/src/voiceformat.h の MUCOM88_VOICEFORMAT):
  8192バイト = 256スロット x 32バイト。各スロットの末尾6バイト(オフセット26-31)が
  name[6]。埋め方はスロットにより不統一(実測: 末尾を空白0x20で埋めるものが大半だが、
  'str3'(4文字)+NUL2個のようにNUL 0x00で埋めているものも存在する)。決め打ちせず、
  生の6バイトをそのまま出力し、末尾の空白/NULを取り除く「正規化」はJS側の
  ui/mucom-voice-resolve.js が実行時に行う(このスクリプトはデータの機械的な
  抽出のみを担当し、意味解釈をしない)。
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "upstream/MucomWeb/mucom88/src/bin_voice.h"
DST = REPO_ROOT / "ui/mucom-voice-table.js"

EXPECTED_SIZE = 8192  # voice_dat_size (bin_voice.h)
SLOT_SIZE = 32
SLOT_COUNT = 256
NAME_OFFSET = 26  # voiceformat.h: name[6]はhed(1)+26バイトのビットフィールド群の直後
NAME_LENGTH = 6


def main() -> int:
    text = SRC.read_text(encoding="ascii")
    match = re.search(r"\{(.*)\}", text, re.DOTALL)
    if not match:
        print(f"error: could not locate array body in {SRC}", file=sys.stderr)
        return 1
    body = match.group(1)
    values = [int(tok, 16) for tok in re.findall(r"0x[0-9a-fA-F]+", body)]
    data = bytes(values)
    if len(data) != EXPECTED_SIZE:
        print(
            f"error: parsed {len(data)} bytes, expected {EXPECTED_SIZE} per bin_voice.h voice_dat_size",
            file=sys.stderr,
        )
        return 1
    if SLOT_SIZE * SLOT_COUNT != EXPECTED_SIZE:
        print("error: SLOT_SIZE*SLOT_COUNT mismatch (internal consistency check)", file=sys.stderr)
        return 1

    entries = []
    for slot in range(SLOT_COUNT):
        off = slot * SLOT_SIZE
        name = data[off + NAME_OFFSET: off + NAME_OFFSET + NAME_LENGTH]
        # 生成物のサイズを小さく保つため、全スロットのうち「値そのものが全く無い」
        # (全6バイトが0x00の)スロットだけは除外する。空白のみ(0x20x6)等の
        # 見た目が空のスロットはここでは判断せず、そのまま含める(意味解釈は
        # ui/mucom-voice-resolve.js側の役目)。
        if name == b"\x00" * NAME_LENGTH:
            continue
        entries.append((slot, name.hex()))

    lines = []
    lines.append("// Generated by tools/gen_mucom_voice_names.py — 手で編集しないこと。")
    lines.append("//")
    lines.append("// 出典: upstream/MucomWeb/mucom88/src/bin_voice.h の bin_voice_dat")
    lines.append("// (MUCOM88既定音色バンク、8192バイト=256スロット×32バイト)。")
    lines.append("// 名前は各スロットのオフセット26-31の6バイト")
    lines.append("// (upstream/MucomWeb/mucom88/src/voiceformat.h の MUCOM88_VOICEFORMAT.name[6]と対応)。")
    lines.append("// ライセンス: MUCOM88由来のデータ、CC BY-NC-SA 4.0。NOTICE.md参照。")
    lines.append("//")
    lines.append("// 全6バイトが0x00(未使用スロット)のエントリのみ除外済み。空白パディング/NULパディングの")
    lines.append("// 区別や、末尾の正規化はここでは行わない(生データをそのまま出す)。")
    lines.append("// 各要素: { slot: スロット番号(0-255), nameHex: 6バイトの生バイト列を16進12桁で表した文字列 }")
    lines.append("export const MUCOM_DEFAULT_VOICE_NAMES = [")
    for slot, name_hex in entries:
        lines.append(f"  {{ slot: {slot}, nameHex: '{name_hex}' }},")
    lines.append("];")
    lines.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DST} ({len(entries)} entries, {SLOT_COUNT - len(entries)} empty slots excluded)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
