#!/usr/bin/env python3
"""upstream/98fmplayer/fmdsp/fmdsp_sprites.h の s_palettes 配列
(PALETTE_NUM=10 パレット x FMDSP_PALETTE_COLORS=10色 x RGB3バイト) を抽出し、
pmdweb/html/fmdsp/palette.js に ES module として出力する。

s_palettes の末尾2パレットは LCD(C)/LCDB(C) マクロ (同ファイル内で定義) を使っており、
このスクリプトは C の定義をそのまま Python で再実装して展開結果を出す。
"""
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC = REPO_ROOT / "upstream/98fmplayer/fmdsp/fmdsp_sprites.h"
DST = REPO_ROOT / "pmdweb/html/fmdsp/palette.js"

# fmdsp_sprites.h:196-210 で定義されているマクロをそのまま再実装する。
LCDWR, LCDWG, LCDWB = 172, 239, 7
LCDBR, LCDBG, LCDBB = 12, 91, 0


def lcd(c: int):
    return (
        (LCDWR * c + LCDBR * (255 - c)) // 256,
        (LCDWG * c + LCDBG * (255 - c)) // 256,
        (LCDWB * c + LCDBB * (255 - c)) // 256,
    )


def lcdb(c: int):
    return (
        (LCDBR * c + LCDWR * (255 - c)) // 256,
        (LCDBG * c + LCDWG * (255 - c)) // 256,
        (LCDBB * c + LCDWB * (255 - c)) // 256,
    )


PALETTE_NUM = 10
COLORS_PER_PALETTE = 10  # FMDSP_PALETTE_COLORS


def main() -> int:
    text = SRC.read_text(encoding="utf-8")
    match = re.search(
        r"static const uint8_t s_palettes\[PALETTE_NUM\]\[FMDSP_PALETTE_COLORS\*3\] = \{(.*?)\n\};",
        text,
        re.DOTALL,
    )
    if not match:
        raise SystemExit(f"error: could not locate s_palettes array in {SRC}")
    body = match.group(1)

    # トップレベルの { ... } ブロックを1パレットずつ切り出す(ネストなしなので単純に対応)。
    palette_blocks = re.findall(r"\{([^{}]*)\}", body, re.DOTALL)
    if len(palette_blocks) != PALETTE_NUM:
        raise SystemExit(
            f"error: found {len(palette_blocks)} palette blocks, expected {PALETTE_NUM}"
        )

    palettes = []
    for block in palette_blocks:
        # トークンは "123," / "LCD(255)," / "LCDB(72)," のいずれか。
        tokens = re.findall(r"LCD\(\s*(\d+)\s*\)|LCDB\(\s*(\d+)\s*\)|(\d+)", block)
        rgb_values = []
        for lcd_arg, lcdb_arg, plain in tokens:
            if lcd_arg != "":
                rgb_values.extend(lcd(int(lcd_arg)))
            elif lcdb_arg != "":
                rgb_values.extend(lcdb(int(lcdb_arg)))
            else:
                rgb_values.append(int(plain))
        if len(rgb_values) != COLORS_PER_PALETTE * 3:
            raise SystemExit(
                f"error: palette has {len(rgb_values)} byte values, "
                f"expected {COLORS_PER_PALETTE * 3}"
            )
        colors = [
            rgb_values[i : i + 3] for i in range(0, len(rgb_values), 3)
        ]
        palettes.append(colors)

    lines = []
    lines.append("// Generated by tools/gen_palette.py from")
    lines.append("// upstream/98fmplayer/fmdsp/fmdsp_sprites.h (s_palettes).")
    lines.append("// Do not edit by hand; re-run the generator instead.")
    lines.append("export const PALETTES = [")
    for colors in palettes:
        row = ", ".join(f"[{r}, {g}, {b}]" for r, g, b in colors)
        lines.append(f"  [{row}],")
    lines.append("];")
    lines.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {DST} ({len(palettes)} palettes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
